### ISSUE TITLE
Unhandled exception. System.InvalidOperationException: There is an error in XML document 

### ISSUE THREAD

**Issue by AlexanderKgr** [smccloud/pfSense-to-OPNSense-Config-File-Converter#12]
Tried version 0.2.1 and again i encounter an issue with xml

![image](https://github.com/smccloud/pfSense-to-OPNSense-Config-File-Converter/assets/25532758/37b21aa8-1040-4bc0-b44b-7ba975f2bde2)

and the part of xml is
![image](https://github.com/smccloud/pfSense-to-OPNSense-Config-File-Converter/assets/25532758/086d6093-b977-42fa-ac1f-4a6d62734f6b)

@smccloud  i suppose it is something like the previous issue

**Comment by smccloud** [comment]
Check release 0.2.2
https://github.com/smccloud/pfSense-to-OPNSense-Config-File-Converter/releases/tag/0.2.2
