### ISSUE TITLE
Strange question at the begging of the script

### ISSUE THREAD

**Issue by AlexanderKgr** [smccloud/pfSense-to-OPNSense-Config-File-Converter#15]
![image](https://github.com/smccloud/pfSense-to-OPNSense-Config-File-Converter/assets/25532758/43d32fe7-2e13-45c2-9483-8e981319897f)

Keep username is Yes or No?
I think something must change.
After selecting Y it asks for password for root. So it yes to keep OPNSense standard of root?

Then it asks for the next users without writing their names

![image](https://github.com/smccloud/pfSense-to-OPNSense-Config-File-Converter/assets/25532758/be121397-9eb6-4ae1-94f5-b443f3f86557)

**Comment by smccloud** [comment]
I'll work on that this weekend. I have a feeling I fat fingered something. It should be putting the username in between the double quotes. As for the root question, pfSense has a user named admin by default and OPNSense has one named root by default. So I offer to convert the admin user from pfSense to root in OPNSense

**Comment by smccloud** [comment]
> I'll work on that this weekend. I have a feeling I fat fingered something. It should be putting the username in between the double quotes. As for the root question, pfSense has a user named admin by default and OPNSense has one named root by default. So I offer to convert the admin user from pfSense to root in OPNSense

I found the possible cause of the issue, even though it shouldn't cause said issue.

**Comment by smccloud** [comment]
Check release 0.2.3
