### ISSUE TITLE
Update for PFSense 23.3

### ISSUE THREAD

**Issue by SimonWellsAus** [smccloud/pfSense-to-OPNSense-Config-File-Converter#27]
Hi mate, needs to be updated to support PFSense 23.3
![pfsense](https://github.com/smccloud/pfSense-to-OPNSense-Config-File-Converter/assets/105570447/ffd0eb46-1bd0-4636-84ad-fd9ad8343ae0)

**Comment by jerry110** [comment]
Yea hes aware ... hes going to take a look at it asap ... check issue 26

**Comment by SimonWellsAus** [comment]
Ok thanks 😀
