### ISSUE TITLE
interface/vlan rename/rearrange support

### ISSUE THREAD

**Issue by Kipjr** [smccloud/pfSense-to-OPNSense-Config-File-Converter#8]
I've built a test environment (pfsense/opnsense) on a VM and I want to migrate it to a physical opnsense. However the hardware NIC names of both are different: em1 or vmx1 and these cause issues with assignments and VLAN. Is it possible to check/modify those in the conversion process?

**Comment by smccloud** [comment]
> I've built a test environment (pfsense/opnsense) on a VM and I want to migrate it to a physical opnsense. However the hardware NIC names of both are different: em1 or vmx1 and these cause issues with assignments and VLAN. Is it possible to check/modify those in the conversion process?

Should be able to. I should have time to work on some of these items this weekend.
