### ISSUE TITLE
Unhandled exception. System.InvalidOperationException: There is an error in XML document

### ISSUE THREAD

**Issue by AlexanderKgr** [smccloud/pfSense-to-OPNSense-Config-File-Converter#9]
![image](https://github.com/smccloud/pfSense-to-OPNSense-Config-File-Converter/assets/25532758/a7e77706-d15a-49fa-a916-f9361affdd30)

Tried with my pfsense xml backup file  and i have this error.

How can i help finding the issue?

I suppose it is something at line 4645

![image](https://github.com/smccloud/pfSense-to-OPNSense-Config-File-Converter/assets/25532758/f3c59074-28ca-42fc-9eee-91a61a15df20)

**Comment by Kipjr** [comment]
```
<rule>
... more stuff 
   <destination>
      <address>alias_host_01</address>
      <port>alias_port_01</port>
   </destination>  <------- <this row gives an error, position 6. It contains 3 tabs before the first character >
... more stuff 
</rule>
```

**Comment by smccloud** [comment]
> ![image](https://github.com/smccloud/pfSense-to-OPNSense-Config-File-Converter/assets/25532758/a7e77706-d15a-49fa-a916-f9361affdd30)
> 
> Tried with my pfsense xml backup file  and i have this error.
> 
> How can i help finding the issue?
> 
> I suppose it is something at line 4645
> 
> ![image](https://github.com/smccloud/pfSense-to-OPNSense-Config-File-Converter/assets/25532758/f3c59074-28ca-42fc-9eee-91a61a15df20)
> 

In your case, it's actually the port range in line 4644. I'll work on it as I have time.

**Comment by smccloud** [comment]
> I've got the same error:
> 
> ```
> <rule>
> ... more stuff 
>    <destination>
>       <address>alias_host_01</address>
>       <port>alias_port_01</port>
>    </destination>  <------- <this row gives an error, position 6. It contains 3 tabs before the first character >
> ... more stuff 
> </rule>
> ```

Probably same basic issue as above, because the line above is not an int but a string.

**Comment by rodeho** [comment]
> > ![image](https://user-images.githubusercontent.com/25532758/279947257-a7e77706-d15a-49fa-a916-f9361affdd30.png)
> > Tried with my pfsense xml backup file  and i have this error.
> > How can i help finding the issue?
> > I suppose it is something at line 4645
> > ![image](https://user-images.githubusercontent.com/25532758/279947807-f3c59074-28ca-42fc-9eee-91a61a15df20.png)
> 
> In your case, it's actually the port range in line 4644. I'll work on it as I have time.

sorry for asking, but I'm into linux script more than windows. In the (very small) readme you suggest to run the "executable"? Im a bit confused which one? 7za seems to be an archiver, so it should be releasebuild.bat. That only provides a lot of sub directories an no questions for config conversion? 

Would you be able to update the readme for linux users ;-) thanks.

This is after running the bat file.

![image](https://github.com/smccloud/pfSense-to-OPNSense-Config-File-Converter/assets/16855935/c66e602c-ae5e-47df-b814-1c92bb2d6fed)

**Comment by rodeho** [comment]
And:

Aliases is corrected by Franco (OPNsense) https://forum.opnsense.org/index.php?topic=36683.msg179282#msg179282
NAT went well via local backup import from pfSense, and don't forget to select only the NAT part from the dropdown.

**Comment by smccloud** [comment]
Should be resolved now.
